### ISSUE TITLE
Can't compile successfully 'src/todo.c'

### ISSUE THREAD

**Issue by N1ma1** [Torbet/Todo#1]
I use `gcc src/todo.c` to compile app , but it returns me :
`src/todo.c:55:6: error: redefinition of ‘addItem’  
   55 | void addItem(char *item) {
      |      ^~~~~~~
src/todo.c:5:6: note: previous definition of ‘addItem’ with type ‘void(char *)’
    5 | void addItem(char *item) {
      |      ^~~~~~~`

**Comment by Torbet** [comment]
Oops! Accidentally added to functions for addItem, duplicates though... can just delete one and should work!

Note: this is unfinished, todos still need to clear automatically after 24 hours

**Comment by N1ma1** [comment]
Oh, lovely.
Its workes :)))
Tnx...
